server:
  port: 50005
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    annotation:
      enabled: true
  data:
    mongodb:
      database: flights
      host: localhost
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
planes:
  service: PLANES
  path: planes
